
package Hotel;
import javax.swing.JOptionPane;

public class InterfazGestionHabitaciones extends javax.swing.JFrame {
    
    private InterfazHotel ventanaPrincipal;

    public InterfazGestionHabitaciones(InterfazHotel ventanaPrincipal) {
        initComponents();
        
        this.ventanaPrincipal = ventanaPrincipal;
        
        cargarTipos();
        cargarHabitaciones();
        mostrarEstado();
    }
private void cargarTipos() {

    cboTipoHabitacion.removeAllItems();

    cboTipoHabitacion.addItem("Simple");
    cboTipoHabitacion.addItem("Doble");
    cboTipoHabitacion.addItem("Suite");
}

private void cargarHabitaciones() {

    cboHabitacion.removeAllItems();

    if (cboTipoHabitacion.getSelectedItem() == null) {
        return;
    }

    String tipo = cboTipoHabitacion.getSelectedItem().toString();

    for (Habitacion h : Contenedor.getInstancia().getHabitaciones()) {

        if (h.getTipo().equals(tipo)) {

            cboHabitacion.addItem(String.valueOf(h.getNumero()));

        }
    }
    }

private void mostrarEstado() {

    if (cboHabitacion.getSelectedItem() == null) {

        lblEstado.setText("");
        btnLiberar.setEnabled(false);

        return;
    }

    int numero = Integer.parseInt(
            cboHabitacion.getSelectedItem().toString());

    Habitacion h =
            Contenedor.getInstancia().buscarHabitacion(numero);

    if (h.isDisponible()) {

        lblEstado.setText("LIBRE");
        btnLiberar.setEnabled(false);

    } else {

        lblEstado.setText("OCUPADA");
        btnLiberar.setEnabled(true);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTipoHabitacion = new javax.swing.JLabel();
        cboTipoHabitacion = new javax.swing.JComboBox<>();
        lblHabitacion = new javax.swing.JLabel();
        cboHabitacion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLiberar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Gestion de Habitaciones");

        lblTipoHabitacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTipoHabitacion.setText("Tipo de Habitacion:");

        cboTipoHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboTipoHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoHabitacionActionPerformed(evt);
            }
        });

        lblHabitacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHabitacion.setText("Habitacion:");

        cboHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboHabitacionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Estado:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnLiberar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLiberar.setText("Liberar");
        btnLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarActionPerformed(evt);
            }
        });

        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        lblEstado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEstado.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHabitacion)
                        .addGap(18, 18, 18)
                        .addComponent(cboHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(lblEstado))
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnLiberar)
                            .addGap(45, 45, 45)
                            .addComponent(btnCerrar))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTipoHabitacion)
                            .addGap(18, 18, 18)
                            .addComponent(cboTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoHabitacion)
                    .addComponent(cboTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHabitacion)
                    .addComponent(cboHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblEstado))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCerrar)
                            .addComponent(btnLiberar))))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void cboTipoHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoHabitacionActionPerformed
        cargarHabitaciones();
        mostrarEstado();
    }//GEN-LAST:event_cboTipoHabitacionActionPerformed

    private void cboHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboHabitacionActionPerformed
        mostrarEstado();
    }//GEN-LAST:event_cboHabitacionActionPerformed

    private void btnLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarActionPerformed
       int numero = Integer.parseInt(
        cboHabitacion.getSelectedItem().toString());

       boolean checkoutRealizado =
        Contenedor.getInstancia().checkout(numero);

     if (checkoutRealizado) {
    cargarHabitaciones();
    mostrarEstado();

    ventanaPrincipal.actualizarVista();

    JOptionPane.showMessageDialog(this,
            "Checkout realizado. La habitación fue liberada.");

} else {
    JOptionPane.showMessageDialog(this,
            "No existe una reserva activa para esta habitación.");


}
    
    }//GEN-LAST:event_btnLiberarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnLiberar;
    private javax.swing.JComboBox<String> cboHabitacion;
    private javax.swing.JComboBox<String> cboTipoHabitacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblHabitacion;
    private javax.swing.JLabel lblTipoHabitacion;
    // End of variables declaration//GEN-END:variables
}
